FROM golang:1.13-alpine as build

RUN mkdir /project
COPY main.go /project/
COPY go.* /project/
WORKDIR /project
RUN go mod vendor
RUN go build -mod=vendor -o /app/main .

FROM alpine:3.7
COPY --from=build /app/main /app/main
WORKDIR /app
CMD /app/main
