FROM golang:1.13-alpine as build_version-json-tagging

RUN mkdir /project
COPY version-json-tagging/* /project/
COPY go.* /project/
WORKDIR /project
RUN go mod vendor
RUN go build -mod=vendor -o /app/main .

FROM alpine:3.7
COPY --from=build_version-json-tagging /app/main /app/main
WORKDIR /app
CMD /app/main

